//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileMaintenanceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcesoDetalle
    {
        public int Id { get; set; }
        public Nullable<int> IdProceso { get; set; }
        public Nullable<long> Weight_file { get; set; }
        public string Extension { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string File_Name { get; set; }
    }
}
