//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileMaintenanceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proceso
    {
        public int IdProcess { get; set; }
        public string ProcessName { get; set; }
        public string Path { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> FileCount { get; set; }
    }
}
